export type CountryEntry = { country: string; continent: string };

export const CONTINENTS = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Oceania",
  "Middle East",
  "Central America & Caribbean",
] as const;

export type Continent = (typeof CONTINENTS)[number];

export const COUNTRIES: CountryEntry[] = [
  // ── Africa ──
  { country: "Algeria", continent: "Africa" },
  { country: "Angola", continent: "Africa" },
  { country: "Benin", continent: "Africa" },
  { country: "Botswana", continent: "Africa" },
  { country: "Burkina Faso", continent: "Africa" },
  { country: "Burundi", continent: "Africa" },
  { country: "Cameroon", continent: "Africa" },
  { country: "Cape Verde", continent: "Africa" },
  { country: "Central African Republic", continent: "Africa" },
  { country: "Chad", continent: "Africa" },
  { country: "Comoros", continent: "Africa" },
  { country: "Congo", continent: "Africa" },
  { country: "DR Congo", continent: "Africa" },
  { country: "Djibouti", continent: "Africa" },
  { country: "Egypt", continent: "Africa" },
  { country: "Equatorial Guinea", continent: "Africa" },
  { country: "Eritrea", continent: "Africa" },
  { country: "Eswatini", continent: "Africa" },
  { country: "Ethiopia", continent: "Africa" },
  { country: "Gabon", continent: "Africa" },
  { country: "Gambia", continent: "Africa" },
  { country: "Ghana", continent: "Africa" },
  { country: "Guinea", continent: "Africa" },
  { country: "Guinea-Bissau", continent: "Africa" },
  { country: "Ivory Coast", continent: "Africa" },
  { country: "Kenya", continent: "Africa" },
  { country: "Lesotho", continent: "Africa" },
  { country: "Liberia", continent: "Africa" },
  { country: "Libya", continent: "Africa" },
  { country: "Madagascar", continent: "Africa" },
  { country: "Malawi", continent: "Africa" },
  { country: "Mali", continent: "Africa" },
  { country: "Mauritania", continent: "Africa" },
  { country: "Mauritius", continent: "Africa" },
  { country: "Morocco", continent: "Africa" },
  { country: "Mozambique", continent: "Africa" },
  { country: "Namibia", continent: "Africa" },
  { country: "Niger", continent: "Africa" },
  { country: "Nigeria", continent: "Africa" },
  { country: "Rwanda", continent: "Africa" },
  { country: "Senegal", continent: "Africa" },
  { country: "Seychelles", continent: "Africa" },
  { country: "Sierra Leone", continent: "Africa" },
  { country: "Somalia", continent: "Africa" },
  { country: "South Africa", continent: "Africa" },
  { country: "South Sudan", continent: "Africa" },
  { country: "Sudan", continent: "Africa" },
  { country: "Tanzania", continent: "Africa" },
  { country: "Togo", continent: "Africa" },
  { country: "Tunisia", continent: "Africa" },
  { country: "Uganda", continent: "Africa" },
  { country: "Zambia", continent: "Africa" },
  { country: "Zimbabwe", continent: "Africa" },

  // ── Asia ──
  { country: "Afghanistan", continent: "Asia" },
  { country: "Bangladesh", continent: "Asia" },
  { country: "Bhutan", continent: "Asia" },
  { country: "Brunei", continent: "Asia" },
  { country: "Cambodia", continent: "Asia" },
  { country: "China", continent: "Asia" },
  { country: "India", continent: "Asia" },
  { country: "Indonesia", continent: "Asia" },
  { country: "Japan", continent: "Asia" },
  { country: "Kazakhstan", continent: "Asia" },
  { country: "Kyrgyzstan", continent: "Asia" },
  { country: "Laos", continent: "Asia" },
  { country: "Malaysia", continent: "Asia" },
  { country: "Maldives", continent: "Asia" },
  { country: "Mongolia", continent: "Asia" },
  { country: "Myanmar", continent: "Asia" },
  { country: "Nepal", continent: "Asia" },
  { country: "North Korea", continent: "Asia" },
  { country: "Pakistan", continent: "Asia" },
  { country: "Philippines", continent: "Asia" },
  { country: "Singapore", continent: "Asia" },
  { country: "South Korea", continent: "Asia" },
  { country: "Sri Lanka", continent: "Asia" },
  { country: "Taiwan", continent: "Asia" },
  { country: "Tajikistan", continent: "Asia" },
  { country: "Thailand", continent: "Asia" },
  { country: "Timor-Leste", continent: "Asia" },
  { country: "Turkmenistan", continent: "Asia" },
  { country: "Uzbekistan", continent: "Asia" },
  { country: "Vietnam", continent: "Asia" },

  // ── Middle East ──
  { country: "Bahrain", continent: "Middle East" },
  { country: "Iran", continent: "Middle East" },
  { country: "Iraq", continent: "Middle East" },
  { country: "Israel", continent: "Middle East" },
  { country: "Jordan", continent: "Middle East" },
  { country: "Kuwait", continent: "Middle East" },
  { country: "Lebanon", continent: "Middle East" },
  { country: "Oman", continent: "Middle East" },
  { country: "Palestine", continent: "Middle East" },
  { country: "Qatar", continent: "Middle East" },
  { country: "Saudi Arabia", continent: "Middle East" },
  { country: "Syria", continent: "Middle East" },
  { country: "Turkey", continent: "Middle East" },
  { country: "UAE", continent: "Middle East" },
  { country: "Yemen", continent: "Middle East" },

  // ── Europe ──
  { country: "Albania", continent: "Europe" },
  { country: "Austria", continent: "Europe" },
  { country: "Belarus", continent: "Europe" },
  { country: "Belgium", continent: "Europe" },
  { country: "Bosnia and Herzegovina", continent: "Europe" },
  { country: "Bulgaria", continent: "Europe" },
  { country: "Croatia", continent: "Europe" },
  { country: "Cyprus", continent: "Europe" },
  { country: "Czech Republic", continent: "Europe" },
  { country: "Denmark", continent: "Europe" },
  { country: "Estonia", continent: "Europe" },
  { country: "Finland", continent: "Europe" },
  { country: "France", continent: "Europe" },
  { country: "Georgia", continent: "Europe" },
  { country: "Germany", continent: "Europe" },
  { country: "Greece", continent: "Europe" },
  { country: "Hungary", continent: "Europe" },
  { country: "Iceland", continent: "Europe" },
  { country: "Ireland", continent: "Europe" },
  { country: "Italy", continent: "Europe" },
  { country: "Kosovo", continent: "Europe" },
  { country: "Latvia", continent: "Europe" },
  { country: "Lithuania", continent: "Europe" },
  { country: "Luxembourg", continent: "Europe" },
  { country: "Malta", continent: "Europe" },
  { country: "Moldova", continent: "Europe" },
  { country: "Montenegro", continent: "Europe" },
  { country: "Netherlands", continent: "Europe" },
  { country: "North Macedonia", continent: "Europe" },
  { country: "Norway", continent: "Europe" },
  { country: "Poland", continent: "Europe" },
  { country: "Portugal", continent: "Europe" },
  { country: "Romania", continent: "Europe" },
  { country: "Russia", continent: "Europe" },
  { country: "Serbia", continent: "Europe" },
  { country: "Slovakia", continent: "Europe" },
  { country: "Slovenia", continent: "Europe" },
  { country: "Spain", continent: "Europe" },
  { country: "Sweden", continent: "Europe" },
  { country: "Switzerland", continent: "Europe" },
  { country: "Ukraine", continent: "Europe" },
  { country: "United Kingdom", continent: "Europe" },

  // ── North America ──
  { country: "Canada", continent: "North America" },
  { country: "Mexico", continent: "North America" },
  { country: "USA", continent: "North America" },

  // ── Central America & Caribbean ──
  { country: "Bahamas", continent: "Central America & Caribbean" },
  { country: "Barbados", continent: "Central America & Caribbean" },
  { country: "Belize", continent: "Central America & Caribbean" },
  { country: "Costa Rica", continent: "Central America & Caribbean" },
  { country: "Cuba", continent: "Central America & Caribbean" },
  { country: "Dominican Republic", continent: "Central America & Caribbean" },
  { country: "El Salvador", continent: "Central America & Caribbean" },
  { country: "Guatemala", continent: "Central America & Caribbean" },
  { country: "Haiti", continent: "Central America & Caribbean" },
  { country: "Honduras", continent: "Central America & Caribbean" },
  { country: "Jamaica", continent: "Central America & Caribbean" },
  { country: "Nicaragua", continent: "Central America & Caribbean" },
  { country: "Panama", continent: "Central America & Caribbean" },
  { country: "Trinidad and Tobago", continent: "Central America & Caribbean" },

  // ── South America ──
  { country: "Argentina", continent: "South America" },
  { country: "Bolivia", continent: "South America" },
  { country: "Brazil", continent: "South America" },
  { country: "Chile", continent: "South America" },
  { country: "Colombia", continent: "South America" },
  { country: "Ecuador", continent: "South America" },
  { country: "Guyana", continent: "South America" },
  { country: "Paraguay", continent: "South America" },
  { country: "Peru", continent: "South America" },
  { country: "Suriname", continent: "South America" },
  { country: "Uruguay", continent: "South America" },
  { country: "Venezuela", continent: "South America" },

  // ── Oceania ──
  { country: "Australia", continent: "Oceania" },
  { country: "Fiji", continent: "Oceania" },
  { country: "New Zealand", continent: "Oceania" },
  { country: "Papua New Guinea", continent: "Oceania" },
  { country: "Samoa", continent: "Oceania" },
  { country: "Solomon Islands", continent: "Oceania" },
  { country: "Tonga", continent: "Oceania" },
  { country: "Vanuatu", continent: "Oceania" },
];

export function countriesForContinent(continent: string): string[] {
  return COUNTRIES.filter(c => c.continent === continent).map(c => c.country);
}

export function continentForCountry(country: string): string {
  return COUNTRIES.find(c => c.country === country)?.continent ?? "";
}
